version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-run:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run start-server-for-test & sleep5
  run-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test
workflows:
    build-and-test:
      jobs:
        - build-and-run
        - run-test