version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-run:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run start-server-for-test && sleep 10
            - run: npm run ci-test

workflows:
    build-and-run:
      jobs:
        - build-and-run